### ISSUE TITLE
Throw a RunTimeException

### ISSUE THREAD

**Issue by lingyun0129** [mayanbin06/FisheyeToPanoramaVideo#1]
log as below:
 Process: com.example.myb.fisheyetopanoramavideo, PID: 31364
                                                   java.lang.RuntimeException: Could not find location for uTextureMatrix
                                                       at com.example.myb.fisheyetopanoramavideo.gles.ShaderProgram.checkLocation(ShaderProgram.java:28)
                                                       at com.example.myb.fisheyetopanoramavideo.gles.ShaderProgram.getUniform(ShaderProgram.java:39)
                                                       at com.example.myb.fisheyetopanoramavideo.gles.SphericalSceneRenderer.<init>(SphericalSceneRenderer.java:35)
                                                       at com.example.myb.fisheyetopanoramavideo.player.SphericalVideoPlayer$RenderThread.onSurfaceAvailable(SphericalVideoPlayer.java:302)
                                                       at com.example.myb.fisheyetopanoramavideo.player.SphericalVideoPlayer$RenderThread.access$500(SphericalVideoPlayer.java:182)
                                                       at com.example.myb.fisheyetopanoramavideo.player.SphericalVideoPlayer$RenderThread$1.handleMessage(SphericalVideoPlayer.java:240)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:207)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lingyun0129** [comment]
how to fix this issue ,thks!

**Comment by mayanbin06** [comment]
这个文件video_vertex_shader.glsl, 你的机器编译gl shader的时候 自动把没用的变量 uTextureMatrix 去掉了.

所以 SphericalSceneRenderer.java中报检查错误, 把文件里的uTextureMatrixLocation变量相关的注释掉试试.

**Comment by lingyun0129** [comment]
@mayanbin06 hi ,注释掉了SphericalSceneRenderer.java中uTextureMatrixLocation相关的代码，运行你的应用，视频却播放不了。你那边能播放你demo中的ten_second.mp4这个视频吗？

错误log如下：
06-06 14:39:07.742 31519-7590/com.example.myb.fisheyetopanoramavideo E/MediaPlayer: stop called in state 0
06-06 14:39:07.742 31519-7590/com.example.myb.fisheyetopanoramavideo E/MediaPlayer: error (-38, 0)
06-06 14:39:07.749 31519-31577/com.example.myb.fisheyetopanoramavideo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7fc7baac50
06-06 14:39:07.795 31519-31519/com.example.myb.fisheyetopanoramavideo E/MultiWindowProxy: getServiceInstance failed!
06-06 14:39:08.561 31519-31536/com.example.myb.fisheyetopanoramavideo E/MediaPlayer: error (1, -2147479551)
06-06 14:39:08.562 31519-13821/com.example.myb.fisheyetopanoramavideo E/MediaPlayer: Error (1,-2147479551)
06-06 14:39:10.424 31519-31577/com.example.myb.fisheyetopanoramavideo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7fc7851a20
06-06 14:39:12.425 31519-31577/com.example.myb.fisheyetopanoramavideo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7fc7cdb6e0

**Comment by lingyun0129** [comment]
补充：是有声音无图像

**Comment by mayanbin06** [comment]
能把改动的diff内容发出来吗？ 我apply试试看。
E/MediaPlayer: error (-38, 0) 从这个错误来看，prepare出问题了？

**Comment by lingyun0129** [comment]
注释掉了SphericalSceneRenderer.java中的以下三行代码
//private int uTextureMatrixLocation;
        //uTextureMatrixLocation =shaderProgram.getUniform("uTextureMatrix");
       // GLES20.glUniformMatrix4fv(uTextureMatrixLocation, 1, false, textureMatrix, 0);

**Comment by mayanbin06** [comment]
我机器上是可用跑的.

**Comment by lingyun0129** [comment]
方便加下QQ吗我的是286240757，thks!

**Comment by victormanuelfrancodev** [comment]
Maybe you have other video in runtime, you need stop this video. 

>   @Override
>      protected void onDestroy() {
>          // メディアプレーヤーを解放する
>          if (videoHolder != null) {
>              videoHolder.stopPlayback();
>              videoHolder = null;
>          }
>          super.onDestroy();
>      };
